version: '3.7'
services:
  app:
    build:
      context: .
      target: production
    env_file: .env
    ports:
      - ${EXPOSE_PORT:-80}:80
    environment:
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-app}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
  cache:
    environment:
      REDIS_HOST: ${REDIS_HOST:-cache}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}
